# <option value="oni1on"></option>
ingredients = [
    "Salt",
    "Pepper (black)",
    "Olive oil",
    "Garlic",
    "Onions",
    "Butter",
    "Eggs",
    "Flour (all-purpose)",
    "Sugar (granulated)",
    "Milk",
    "Tomatoes",
    "Rice",
    "Chicken",
    "Beef",
    "Pasta",
    "Potatoes",
    "Lemon",
    "Vinegar (white)",
    "Soy sauce",
    "Ginger",
    "Cumin",
    "Paprika",
    "Oregano",
    "Basil",
    "Thyme",
    "Rosemary",
    "Bay leaves",
    "Parsley",
    "Cinnamon",
    "Nutmeg",
    "Coriander (ground or seeds)",
    "Turmeric",
    "Mustard (ground or seeds)",
    "Honey",
    "Worcestershire sauce",
    "Sesame oil",
    "Coconut milk",
    "Fish sauce",
    "Stock (chicken, beef, vegetable)",
    "Parmesan cheese",
    "Cheddar cheese",
    "Mozzarella cheese",
    "Feta cheese",
    "Yogurt",
    "Sour cream",
    "Green onions/scallions",
    "Bell peppers (red, green, yellow)",
    "Carrots",
    "Celery",
    "Lemon juice"
]
for i in ingredients:
    print(f'<option value="{i}"></option>') 